rules:
  max-ten:
    - max: 3
  spellcheck-tech-word: true
  no-mix-dearu-desumasu: true
filters:
  comments: true
  whitelist:
    allow:
      # amp-youtube etc.
      - /\S-\S/
      # `===IGNORE===`で囲んだ範囲
      - /===IGNORE===[\\s\\S]*?===\/IGNORE===/m