name = "blog"
main = "src/index.tsx"
compatibility_date = "2024-12-31"

[vars]
SITE_AUTHOR = "Hirofumi Miyamoto"
SITE_TITLE = "iiyatsu - hrfmmymt's weblog"
SITE_DESCRIPTION = "hrfmmymt's weblog"
SITE_URL = "https://iiyatsu.hrfmmymt.com/"
SITE_OG_IMAGE = "/img/icon/icon.png"
GA_ID = "G-SXQ1HCL844"

[site]
bucket = "./public"
