name: test and build iiyatsu
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: yarn
      - run: yarn test
      - run: yarn build
